name: CI
on:
  push:
    branches:
      - master
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        features:
         - "" # only core
         - --features=alloc # core + alloc
         - --features=std # whole std
    steps:
      - uses: actions/checkout@v2
      - run:
          cargo test --no-default-features ${{ matrix.features }}
